export const colors = {
  sidebar: '#4f46e5',
  sidebarActive: '#4338ca',
  sidebarHighlight: '#4f46e5',
  pageBg: '#111827',
  cardBg: '#1f2937',
  cardBorder: '#374151',
  headerBg: '#1f2937',
  textPrimary: '#f3f4f6',
  textSecondary: '#9ca3af',
  textMuted: '#e0e7ff',
  textWhite: '#ffffff',
  textWhiteMuted: 'rgba(255,255,255,0.64)',
  inputBg: '#374151',
  inputBorder: '#4b5563',
  searchIcon: '#94a3b8',
  accent: '#4f46e5',
  chartBlue: '#1ea7ff',
  chartPurple: '#5051f9',
  chartGrid: '#e7ebec',
  chartAxis: '#e5e7ea',
  chartMonth: '#f9f9f9',
  tabInactive: '#aeaed3',
  online: '#4ade80',
  admin: '#c7d2fe',
};

export const fonts = {
  inter: 'var(--font-inter), Inter, sans-serif',
  dmSans: 'var(--font-dm-sans), "DM Sans", sans-serif',
  poppins: 'var(--font-poppins), Poppins, sans-serif',
  abhaya: 'var(--font-abhaya), "Abhaya Libre", serif',
};

export const projects = [
  {
    initial: 'W',
    iconColor: '#4f46e5',
    status: 'Active',
    statusBg: '#14532d',
    statusColor: '#bbf7d0',
    title: 'Website Redesign',
    description: 'Redesign company website with new branding',
    progress: 65,
    progressColor: '#4f46e5',
    members: 3,
  },
  {
    initial: 'M',
    iconColor: '#8b5cf6',
    status: 'Active',
    statusBg: '#14532d',
    statusColor: '#bbf7d0',
    title: 'Mobile App Development',
    description: 'Build iOS and Android app for the platform',
    progress: 35,
    progressColor: '#8b5cf6',
    members: 3,
  },
  {
    initial: 'M',
    iconColor: '#ec4899',
    status: 'On-hold',
    statusBg: '#713f12',
    statusColor: '#fef08a',
    title: 'Marketing Campaign',
    description: 'Q4 marketing campaign for product launch',
    progress: 15,
    progressColor: '#ec4899',
    members: 2,
  },
  {
    initial: 'U',
    iconColor: '#10b981',
    status: 'Completed',
    statusBg: '#1e3a8a',
    statusColor: '#bfdbfe',
    title: 'User Research',
    description: 'Conduct user interviews and surveys',
    progress: 100,
    progressColor: '#10b981',
    members: 2,
  },
  {
    initial: 'C',
    iconColor: '#f59e0b',
    status: 'Active',
    statusBg: '#14532d',
    statusColor: '#bbf7d0',
    title: 'Content Strategy',
    description: 'Develop content plan for blog and social media',
    progress: 40,
    progressColor: '#f59e0b',
    members: 2,
    tall: true,
  },
];

export const navItems = [
  { id: 'dashboard', label: 'Dashboard', active: true },
  { id: 'projects', label: 'Projects' },
  { id: 'team', label: 'Team' },
  { id: 'settings', label: 'Settings' },
  { id: 'files', label: 'Files', highlight: true },
  { id: 'updates', label: 'All Updates', icon: 'clock' },
];
